import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)

const NOMENCLATOR: Record<string, string> = {
  'eritrocite': 'Eritrocite',
  'nr. eritrocite': 'Eritrocite',
  'numar eritrocite': 'Eritrocite',
  'globule rosii': 'Eritrocite',
  'rbc': 'Eritrocite',
  'hemoglobina': 'Hemoglobina',
  'hemoglobina (hb)': 'Hemoglobina',
  'hb': 'Hemoglobina',
  'hgb': 'Hemoglobina',
  'hematocrit': 'Hematocrit',
  'ht': 'Hematocrit',
  'hct': 'Hematocrit',
  'volum eritrocitar mediu': 'Volum eritrocitar mediu (VEM)',
  'volum eritrocitar mediu (vem)': 'Volum eritrocitar mediu (VEM)',
  'vem': 'Volum eritrocitar mediu (VEM)',
  'mcv': 'Volum eritrocitar mediu (VEM)',
  'hemoglobina eritrocitara medie': 'Hemoglobina eritrocitara medie (HEM)',
  'hemoglobina eritrocitara medie (hem)': 'Hemoglobina eritrocitara medie (HEM)',
  'hem': 'Hemoglobina eritrocitara medie (HEM)',
  'mch': 'Hemoglobina eritrocitara medie (HEM)',
  'concentratie medie hb/eritrocit': 'Concentratie medie Hb/eritrocit (CHEM)',
  'concentratie medie a hb/eritrocit': 'Concentratie medie Hb/eritrocit (CHEM)',
  'chem': 'Concentratie medie Hb/eritrocit (CHEM)',
  'mchc': 'Concentratie medie Hb/eritrocit (CHEM)',
  'largimea distributiei eritrocitare': 'Largimea distributiei eritrocitare (RDW)',
  'rdw': 'Largimea distributiei eritrocitare (RDW)',
  'leucocite': 'Leucocite',
  'nr. leucocite': 'Leucocite',
  'numar leucocite': 'Leucocite',
  'globule albe': 'Leucocite',
  'wbc': 'Leucocite',
  'neutrofile %': 'Neutrofile %',
  'neutrofil %': 'Neutrofile %',
  'neutrofil (%)': 'Neutrofile %',
  'gran %': 'Neutrofile %',
  'neut %': 'Neutrofile %',
  'neutrofile absolute': 'Neutrofile absolute',
  'neutrofil abs': 'Neutrofile absolute',
  'neutrofil (abs)': 'Neutrofile absolute',
  'neutrofil (#)': 'Neutrofile absolute',
  'limfocite %': 'Limfocite %',
  'limfocit %': 'Limfocite %',
  'limfocit (%)': 'Limfocite %',
  'limfocite absolute': 'Limfocite absolute',
  'limfocit abs': 'Limfocite absolute',
  'limfocit (abs)': 'Limfocite absolute',
  'limfocit (#)': 'Limfocite absolute',
  'monocite %': 'Monocite %',
  'monocit %': 'Monocite %',
  'monocit (%)': 'Monocite %',
  'monocite absolute': 'Monocite absolute',
  'monocit abs': 'Monocite absolute',
  'monocit (abs)': 'Monocite absolute',
  'eozinofile %': 'Eozinofile %',
  'eozinofil %': 'Eozinofile %',
  'eozinofil (%)': 'Eozinofile %',
  'eozinofile absolute': 'Eozinofile absolute',
  'eozinofil abs': 'Eozinofile absolute',
  'eozinofil (abs)': 'Eozinofile absolute',
  'bazofile %': 'Bazofile %',
  'bazofil %': 'Bazofile %',
  'bazofil (%)': 'Bazofile %',
  'bazofile absolute': 'Bazofile absolute',
  'bazofil abs': 'Bazofile absolute',
  'bazofil (abs)': 'Bazofile absolute',
  'trombocite': 'Trombocite',
  'nr. trombocite': 'Trombocite',
  'numar trombocite': 'Trombocite',
  'plt': 'Trombocite',
  'volum trombocitar mediu': 'Volum trombocitar mediu (VTM)',
  'volum trombocitar mediu (vtm)': 'Volum trombocitar mediu (VTM)',
  'vtm': 'Volum trombocitar mediu (VTM)',
  'mpv': 'Volum trombocitar mediu (VTM)',
  'largimea distributiei trombocitare': 'Largimea distributiei trombocitare (PDW)',
  'pdw': 'Largimea distributiei trombocitare (PDW)',
  'reticulocite %': 'Reticulocite %',
  'reticulocite abs': 'Reticulocite absolute',
  'vsh': 'VSH',
  'viteza de sedimentare a hematiilor': 'VSH',
  'esr': 'VSH',
  'timp de protrombina': 'Timp de protrombina (TP)',
  'tp': 'Timp de protrombina (TP)',
  'inr': 'INR',
  'procente de protrombina': 'Activitate protrombina %',
  'aptt': 'aPTT',
  'aptt actin fs': 'aPTT',
  'fibrinogen': 'Fibrinogen',
  'd-dimeri': 'D-Dimeri',
  'd dimeri': 'D-Dimeri',
  'glucoza': 'Glucoza',
  'glucoza serica': 'Glucoza',
  'glicemie': 'Glucoza',
  'hemoglobina glicata hba1c': 'Hemoglobina glicata (HbA1c)',
  'hemoglobina glicata': 'Hemoglobina glicata (HbA1c)',
  'hba1c': 'Hemoglobina glicata (HbA1c)',
  'insulina': 'Insulina',
  'homa-ir': 'HOMA-IR',
  'homa ir': 'HOMA-IR',
  'colesterol total': 'Colesterol total',
  'colesterol': 'Colesterol total',
  'colesterol hdl': 'Colesterol HDL',
  'hdl colesterol': 'Colesterol HDL',
  'hdl': 'Colesterol HDL',
  'colesterol ldl': 'Colesterol LDL',
  'ldl colesterol': 'Colesterol LDL',
  'ldl': 'Colesterol LDL',
  'trigliceride': 'Trigliceride',
  'alt (tgp)': 'ALT (TGP)',
  'alt': 'ALT (TGP)',
  'tgp': 'ALT (TGP)',
  'alat': 'ALT (TGP)',
  'alaninaminotransferaza': 'ALT (TGP)',
  'alaninaminotransferaza (gpt/alat/alt)': 'ALT (TGP)',
  'alaninaminotransferaza (gpt/alt)': 'ALT (TGP)',
  'ast (tgo)': 'AST (TGO)',
  'ast': 'AST (TGO)',
  'tgo': 'AST (TGO)',
  'asat': 'AST (TGO)',
  'aspartataminotransferaza': 'AST (TGO)',
  'aspartataminotransferaza (got/asat/ast)': 'AST (TGO)',
  'aspartataminotransferaza (got/ast)': 'AST (TGO)',
  'ggt': 'GGT',
  'gamma-glutamiltransferaza': 'GGT',
  'fosfataza alcalina': 'Fosfataza alcalina',
  'alp': 'Fosfataza alcalina',
  'bilirubina totala': 'Bilirubina totala',
  'bilirubina': 'Bilirubina totala',
  'bilirubina directa': 'Bilirubina directa',
  'bilirubina indirecta': 'Bilirubina indirecta',
  'proteine totale': 'Proteine totale',
  'albumina': 'Albumina',
  'creatinina': 'Creatinina',
  'creatinina serica': 'Creatinina',
  'egfr': 'eGFR',
  'uree': 'Uree',
  'uree serica': 'Uree',
  'acid uric': 'Acid uric',
  'sodiu': 'Sodiu',
  'sodiu seric': 'Sodiu',
  'potasiu': 'Potasiu',
  'potasiu seric': 'Potasiu',
  'calciu': 'Calciu',
  'calciu seric': 'Calciu',
  'calciu ionic': 'Calciu ionic',
  'magneziu': 'Magneziu',
  'fosfor': 'Fosfor',
  'fier': 'Fier seric',
  'fier seric': 'Fier seric',
  'feritina': 'Feritina',
  'transferina': 'Transferina',
  'tibc': 'TIBC',
  'amilaza': 'Amilaza',
  'amilaza serica': 'Amilaza',
  'lipaza': 'Lipaza',
  'lipaza serica': 'Lipaza',
  'lipaza serică': 'Lipaza',
  'proteina c reactiva': 'Proteina C reactiva (CRP)',
  'crp': 'Proteina C reactiva (CRP)',
  'homocisteina': 'Homocisteina',
  'tsh': 'TSH',
  'tsh (hormon de stimulare tiroidiana)': 'TSH',
  'tsh (h. de stimulare tiroidiana)': 'TSH',
  't3': 'T3 total',
  'ft3': 'FT3',
  't3 liber': 'FT3',
  'free t3': 'FT3',
  't4': 'T4 total',
  'ft4': 'FT4',
  't4 liber': 'FT4',
  'free t4': 'FT4',
  'free t4 (ft4 - tiroxina libera)': 'FT4',
  'anti-tpo': 'Anti-TPO',
  'anti tpo': 'Anti-TPO',
  'anti-tiroidperoxidaza': 'Anti-TPO',
  'anti-tiroglobulina': 'Anti-tiroglobulina',
  'anti tiroglobulina': 'Anti-tiroglobulina',
  'tiroglobulina': 'Tiroglobulina',
  'tiroglobulina high sensitive (hstg)': 'Tiroglobulina',
  'pth': 'PTH intact',
  'pth intact': 'PTH intact',
  'pth intact (parathormon)': 'PTH intact',
  'parathormon': 'PTH intact',
  'cortizol': 'Cortizol',
  'dhea-s': 'DHEA-S',
  'dhea': 'DHEA-S',
  'dhea-s (dehidroepiandrosteron sulfat)': 'DHEA-S',
  'vitamina d': 'Vitamina D (25-OH)',
  'vitamina d-25-hydroxyvit d': 'Vitamina D (25-OH)',
  '25-oh vitamina d': 'Vitamina D (25-OH)',
  'fsh': 'FSH',
  'lh': 'LH',
  'estradiol': 'Estradiol (E2)',
  'progesteron': 'Progesteron',
  'prolactina': 'Prolactina',
  'testosteron': 'Testosteron total',
  'testosteron total': 'Testosteron total',
  'testosteron liber': 'Testosteron liber',
  'amh': 'AMH',
  'beta-hcg': 'Beta-HCG',
  'hcg': 'Beta-HCG',
  'vitamina b12': 'Vitamina B12',
  'acid folic': 'Acid folic (B9)',
  'folat': 'Acid folic (B9)',
  'zinc': 'Zinc',
  'seleniu': 'Seleniu',
  'cupru': 'Cupru',
  'iga': 'IgA',
  'igg': 'IgG',
  'igm': 'IgM',
  'ige total': 'IgE total',
  'ige': 'IgE total',
  'ana': 'ANA',
  'factor reumatoid': 'Factor reumatoid (FR)',
  'anti-ccp': 'Anti-CCP',
  'hbsag': 'HBsAg (Hepatita B)',
  'anti-hbs': 'Anti-HBs (Hepatita B)',
  'anti-hcv': 'Anti-HCV (Hepatita C)',
  'anti-hiv': 'Anti-HIV',
  'psa': 'PSA total',
  'psa total': 'PSA total',
  'psa liber': 'PSA liber',
  'cea': 'CEA',
  'afp': 'AFP',
  'ca 125': 'CA 125',
  'ca125': 'CA 125',
  'ca 19-9': 'CA 19-9',
  'ca19-9': 'CA 19-9',
  'ca 15-3': 'CA 15-3',
  'troponina': 'Troponina I',
  'bnp': 'BNP',
  'nt-probnp': 'NT-proBNP',
  'ck-mb': 'CK-MB',
  'antigen streptococ betahemolitic grup a': 'Ag Streptococ grup A',
  'sumar urina': 'Sumar urina',
  'examen sumar urina': 'Sumar urina',
  'microalbuminurie': 'Microalbuminurie',
  'examen coproparazitologic': 'Examen coproparazitologic',
  'coproparazitologic': 'Examen coproparazitologic',
}

function normalizeaza(nume: string): string {
  const lower = nume.toLowerCase().trim()
    .replace(/ă/g, 'a').replace(/â/g, 'a').replace(/î/g, 'i')
    .replace(/ș/g, 's').replace(/ş/g, 's')
    .replace(/ț/g, 't').replace(/ţ/g, 't')
  return NOMENCLATOR[lower] || nume
}

export async function GET() {
  try {
    const { data: analize, error } = await supabase
      .from('analize')
      .select('id, nume_analiza')

    if (error) return NextResponse.json({ error: error.message }, { status: 500 })

    let actualizate = 0
    for (const analiza of (analize || [])) {
      const numeNou = normalizeaza(analiza.nume_analiza)
      if (numeNou !== analiza.nume_analiza) {
        await supabase.from('analize').update({ nume_analiza: numeNou }).eq('id', analiza.id)
        actualizate++
      }
    }

    return NextResponse.json({ success: true, actualizate, total: analize?.length })
  } catch (e) {
    return NextResponse.json({ error: String(e) }, { status: 500 })
  }
}